### ISSUE TITLE
AI translation error

### ISSUE THREAD

**Issue by YomostXme** [codynhanpham/jp-to-en-ocr#2]
It's me again. I tried to translate with AI-assisted but i kept getting this error. I already installed the recommend model, updated the CMD-FLAGS.txt and .env file
![image](https://github.com/codynhanpham/jp-to-en-ocr/assets/107755697/9d7f454d-c5dc-4e8e-b0d5-7090d519eda2)
![image](https://github.com/codynhanpham/jp-to-en-ocr/assets/107755697/71da8032-9a15-48da-8721-e6371f1ddabf)
![image](https://github.com/codynhanpham/jp-to-en-ocr/assets/107755697/a159288e-aaeb-48db-9e1c-d308e7d70d75)

**Comment by codynhanpham** [comment]
Hi again! Sorry for the late reply, I do have a full-time job so I can only work on my personal stuff on the weekend lol

Okay, just to make sure, for the `.env` file, the `AI_API_SERVER` should be the default value (`http://127.0.0.1:5000`), right? What happens when you go to `http://127.0.0.1:5000/docs` on your browser? Can you also try and replace `--extensions openai` with `--api --listen`?

While we are figuring this out, you can also change `SHOW_ML` in the `.env` file to `SHOW_ML="true"` to show the machine translations. At least we will know if it's just the AI part that is bugged.
 
I have not updated the oobabooga app on my machine for a while, but I checked the current document on [their wiki](https://github.com/oobabooga/text-generation-webui/wiki/12-%E2%80%90-OpenAI-API) and the code are the same, so I can't see why it's not working. 

Have you tried translating other text? Besides screen snip to do OCR, you can also just Ctrl+C to copy Japanese text to translate! Maybe sentences like `最後にオオカミはとても疲れ横になり、完全に疲れ果てていました。`

Meanwhile, let me try things out to see if I can reproduce the same error.

**Comment by codynhanpham** [comment]
Oh right I found the problem. Oobabooga updated on their end. I will work on updating the code!

**Comment by codynhanpham** [comment]
@YomostXme 
Alright! Got it fixed. You can update the app by running `git pull`.

Super weird that the API now uses `"delta"` instead of `"message"`. Well, whatever, I guess? I looked around and there was no mention of this change at all in oobabooga github repo and discord.

---

Edit: I have been testing the AI translation again for the last couple of hours. Something really changed the AI response; it is really bad now for some reason. Since the last update 3 months ago, using the old oobabooga version, I could read an entire manga volume with just the AI translation. Now, it's unusable. No idea what changed :)

It will take a while to test things out and find good parameters for a particular model. Well, in the meantime...

You can try it out anyway, and if you want to dig deeper, the AI parameters are in `main.py`, around line 47 (`request` variable). You can also change the translation examples in `./ai_translate/base_history.json`.

**Comment by YomostXme** [comment]
Yeah the ai translation is now even worse than the machine ones. Also thanks for fixing the issue
